non-standard notify service support
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@111605 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/LGPL/CommonSoftware/acsstartup/src/acsstartupPids b/LGPL/CommonSoftware/acsstartup/src/acsstartupPids
--- a/LGPL/CommonSoftware/acsstartup/src/acsstartupPids
+++ b/LGPL/CommonSoftware/acsstartup/src/acsstartupPids
@@ -73,6 +73,31 @@ echo $PID
 }
 export getPid
 #-------------------------------------
+#Sends the process ID of some process to stdout or returns with an
+#error code if there's some failure.
+function getServicePid
+{
+local INSTANCE_DIR
+local SERVICE_NAME
+local FILE
+local PID
+local PORT
+
+INSTANCE_DIR=`getInstanceDirName $ACS_INSTANCE`
+SERVICE_NAME=$1
+FILE=$2
+PORT=$3
+
+if ! PID=`getPid $FILE $PORT`
+then
+    ACS_LOG_ERROR "acsstartupPids" "Unable to determine ${SERVICE_NAME}'s process ID."
+    exit $EC_FAILURE
+fi
+
+echo $PID
+}
+export getServicePid
+#-------------------------------------
 #Sends the process ID of manager to stdout or returns with an 
 #error code if there's some failure.
 function getManagerPid
