removed ksh usage and switched to bash, which is installed by default in most linux distributions (and cygwin) cleaned up searchFile, added some error messages
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@135278 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/LGPL/Kit/vlt/src/searchFile b/LGPL/Kit/vlt/src/searchFile
--- a/LGPL/Kit/vlt/src/searchFile
+++ b/LGPL/Kit/vlt/src/searchFile
@@ -1,12 +1,13 @@
-#!/bin/ksh
+#!/bin/sh
 #************************************************************************
 # E.S.O. - ALMA project
 #
-# "@(#) $Id: searchFile,v 1.1 2004/09/15 13:36:58 mpasquat Exp $"
+# "@(#) $Id: searchFile,v 1.2 2010/07/09 12:48:42 alopatin Exp $"
 #
 # who       when        what
 # --------  ----------  -------------------------------------------------
 # mpasquat  2004-JUL-19 created
+# alopatin  2010-JUL-08 switched to POSIX standard /bin/sh
 
 #************************************************************************
 #   NAME 
@@ -36,48 +37,30 @@
 #
 #------------------------------------------------------------------------
 
-
-file=$1
-if [ "X$1" == "X" ]
+if [ "X$1" = "X" ]
 then
-   print "#error#"
+   echo "No filename provided. Usage: $0 <filename>" >&2
+   echo "#error#"
    exit 0
 fi
 
-if [ "X$INTROOT" != "X" ]
-then
-   if  [ -f $INTROOT/$file ]
-   then
-      print $INTROOT
-      exit 0  
-   fi  
-fi
+file=$1
+SEARCHPATH="$INTROOT:$INTLIST:$ACSROOT"
 
-if [ "X$INTLIST" != "X" ]
+if [ "X$SEARCHPATH" != "X::" ]
 then
-   INTLIST_LIST=`echo $INTLIST | sed s/\:/\ /g`
-   for dir in $INTLIST_LIST
+   PATH_LIST=`echo $SEARCHPATH | sed s/\:/\ /g`
+   for dir in $PATH_LIST
    do
       if  [ -f $dir/$file ]
       then
-         print $dir
-         exit 0   
-      fi 
+         echo $dir
+         exit 0
+      fi
    done
-fi
-   
-if [ "X$ACSROOT" != "X" ]
-then
-   if  [ -f $ACSROOT/$file ]
-   then
-      print $ACSROOT
-      exit 0
-   else
-      print "#error#"
-   fi
+   echo "File $file not found in your ACS installation." >&2
+   echo "#error#"
 else
-   print "#error#"
+   echo "$file not found. Environment variables INTROOT, ACSROOT and INTLIST are empty. Did you source the .bash_profile.acs?" >&2
+   echo "#error#"
 fi
-
-
-
