Updated to work properly with ACS/Makefile, i.e. it requires a series of special targets for that purpose. These targets were copied over from the Makefile of CS/LGPL/CommonSoftware/ACSLaser.
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@81062 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/LGPL/CommonSoftware/containerTests/Makefile b/LGPL/CommonSoftware/containerTests/Makefile
--- a/LGPL/CommonSoftware/containerTests/Makefile
+++ b/LGPL/CommonSoftware/containerTests/Makefile
@@ -16,13 +16,14 @@
 # License along with this library; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 #
-# "@(#) $Id: Makefile,v 1.1.1.1 2007/11/13 14:25:38 eallaert Exp $"
+# "@(#) $Id: Makefile,v 1.2 2007/12/14 13:13:46 eallaert Exp $"
 #
 # Makefile of containerTests (the package dealing with container tests)
 #
 # who       when        what
 # --------  ----------  ----------------------------------------------
 # eallaert  2007-11-13  created
+# eallaert  2007-12-14  updated to work with ACS/Makefile
 #
 #*******************************************************************************
 # This Makefile follows ACS Standards (see Makefile(5) for more).
@@ -34,26 +35,13 @@
 #
 # Modules in the various containerTest sub-packages.
 #
+MODULES =  contLogTest 
 SUBSYSTEM = "containerTest"
 
-MODULES =  contLogTest 
-
-#
-# If option KEEP_GOING=on is present in the make command line gnu_make is NOT interrupted 
-# when the first error is encountered
-#
-
-ifdef KEEP_GOING
-   KEEP_GOING="on"
-else
-   KEEP_GOING="off"
+ifeq ($(os) $(VXWORKS_RTOS),Linux NO)
+    MAKE_FLAGS = "NOCCS=1"
 endif
 
-RETURN_CODE=return_code
-TMP_RETURN_CODE=tmp_return_code
-
-MAKE_FLAGS = "-k"
-PLATFORM := $(shell uname)
 
 SHELL=/bin/ksh
 ECHO=echo
@@ -69,42 +57,7 @@ endif
 os     = $(shell uname)
 osrev  = $(shell uname -r)
 
-ifeq ($(os),SunOS)
-	realtime=YES
-endif
-
-#
-# "Failed all" error management
-#
-define mng_failed_all
-	if [[ -a  $(TMP_RETURN_CODE) ]]; then\
-		$(ECHO) "### ==> FAILED all ! " | tee -a build.log | tee -a $(RETURN_CODE);\
-		rm $(TMP_RETURN_CODE);\
-		if [[ $(KEEP_GOING) = "off" ]]; then \
-			if [[ -a $(RETURN_CODE) ]]; then \
-				rm $(RETURN_CODE);\
-			fi;\
-			exit 2;\
-		fi;\
-	fi 
-endef
-
-#
-# "Failed install" error management
-#
-define mng_failed_install
-	if [[ -a  $(TMP_RETURN_CODE) ]]; then\
-		$(ECHO) "### ==> FAILED install ! " | tee -a build.log | tee -a $(RETURN_CODE);\
-		rm $(TMP_RETURN_CODE);\
-		if [[ $(KEEP_GOING) = "off" ]]; then \
-			if [[ -a $(RETURN_CODE) ]]; then \
-				rm $(RETURN_CODE);\
-			fi;\
-			exit 2;\
-		fi;\
-	fi 
-endef
-
+startupDir = $(shell pwd)
 
 #
 # This target just forward any make target to all modules
@@ -121,7 +74,7 @@ define canned
 		    elif [ -f $${member}/ws/src/Makefile ]; then \
 			$(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ $@ || break ;\
 		    fi;\
-		    if [ "$(realtime)" == "YES" ]; then \
+		    if [ "$(VXWORKS_RTOS)" == "YES" ]; then \
 			if [ -f $${member}/lcu/src/Makefile ]; then \
 			$(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ $@ || break ;\
 			fi;\
@@ -129,84 +82,213 @@ define canned
 		done
 endef
 
+#
+# This target builds and installs all containerTest modules on a clean
+# directory structure.
+# Per each module it executes:
+#    make clean all install
+#
+build: 	clean_log update
+	@$(ECHO) "... done"
+
+#
+# This target builds and installs all containerTest modules on a clean
+# directory structure.
+# Per each module it executes:
+#    make clean all man install clean
+#
+build_clean:   	clean_log update_clean
+	@$(ECHO) "... done"
+
+#
+# This target builds and installs all containerTest modules on a clean 
+# directory structure.
+# Per each module it executes:
+#    make clean all man install clean
+# then, before going to the next module, tries to run the
+# modular test.
+# This is useful to discover circular dependencies between
+# modules.
+#
+build_clean_test:   	clean_log update_clean_test
+	@$(ECHO) "... done"
+
+#
+# This target re-builds and installs all containerTest modules on an  
+# existing directory structure.
+# Per each module it executes:
+#    make clean all man install clean
+#
+rebuild:	clean_log update
+	@$(ECHO) "... done"
+
 clean_log:
 	@$(ECHO) "############ Clean Build Log File: build.log #################"
 	@rm -f build.log
 	@touch build.log
 
+clean_test_log:
+	@$(ECHO) "############ Clean Test Log File: test.log #################"
+	@rm -f test.log
+	@touch test.log
+
+
 #
-# building all modules
+# Update of all core components
+# According to SE standards does not make man and does not clenup at the end.
 #
-build:	
-	@$(ECHO) "############ build $(SUBSYSTEM) Software         #################"| tee -a build.log
-	@# Deletion of temporary files used to store make return code
-	@if [[ -a $(TMP_RETURN_CODE) ]]; then \
-		rm $(TMP_RETURN_CODE);\
-	fi
-	@if [[ -a $(RETURN_CODE) ]]; then \
-		rm $(RETURN_CODE);\
-	fi
+# There is a 'true' at the end of the loop to ensure  that if the LAST
+#  module fails the whole Make does not fail
+#
+
+update:
+	@$(ECHO) "############ (Re-)build$ (SUBSYSTEM) Software         #################"| tee -a build.log
 	@for member in  $(foreach name, $(MODULES), $(name) ) ; do \
-		    if [ ! -d $${member} ]; then \
-			echo "### ==> $${member} MODULE NOT FOUND! FAILED! " | tee -a build.log;\
-		    fi;\
-		    if [ -f $${member}/src/Makefile ]; then \
-		         $(ECHO) "############ $${member} MAIN" | tee -a build.log;\
-			 $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ clean >> build.log 2>& 1;\
-			 $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ all >> build.log 2>& 1 || echo $$? >> $(TMP_RETURN_CODE) ;\
-			 $(mng_failed_all);\
-			 $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ install >> build.log 2>& 1 || echo $$? >> $(TMP_RETURN_CODE) ;\
-			 $(mng_failed_install);\
-			 continue ;\
-		    fi;\
-		    if [ -f $${member}/ws/src/Makefile ]; then \
-			 $(ECHO) "############ $${member} WS" | tee -a build.log;\
-			 $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ clean >> build.log 2>& 1;\
-			 $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ all >> build.log 2>& 1 || echo $$? >> $(TMP_RETURN_CODE) ;\
-			 $(mng_failed_all);\
-			 $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ install >> build.log 2>& 1 || echo $$? >> $(TMP_RETURN_CODE) ;\
-			 $(mng_failed_install);\
-		    fi;\
-		    if [ "$(realtime)" == "YES" ]; then \
-			if [ -f $${member}/lcu/src/Makefile ]; then \
-			    $(ECHO) "############ $${member} LCU" | tee -a build.log;\
-			    $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ clean >> build.log 2>& 1;\
-			    $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ all >> build.log 2>& 1 || echo $$? >> $(TMP_RETURN_CODE) ;\
-			    $(mng_failed_all);\
-			    $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ install >> build.log 2>& 1 || echo $$? >> $(TMP_RETURN_CODE) ;\
-			    $(mng_failed_install);\
-			fi;\
-		    fi;\
-		done
-		@$(ECHO) "... done"
+	    if [ ! -d $${member} ]; then \
+                 echo "######## ==> $${member} MODULE NOT FOUND! FAILED! " | tee -a build.log;\
+            fi;\
+	    if [ -f $${member}/src/Makefile ]; then \
+	        $(ECHO) "############ $${member} MAIN" | tee -a build.log;\
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ clean >> build.log 2>& 1;\
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ all >> build.log 2>& 1 || echo "### ==> FAILED all ! " | tee -a build.log; \
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ install >> build.log 2>& 1 || echo "### ==> FAILED install ! " | tee -a build.log; \
+	    elif [ -f $${member}/ws/src/Makefile ]; then \
+		$(ECHO) "############ $${member} WS" | tee -a build.log;\
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ clean >> build.log 2>& 1;\
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ all >> build.log 2>& 1 || echo "### ==> FAILED all ! " | tee -a build.log; \
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ install >> build.log 2>& 1 || echo "### ==> FAILED install ! " | tee -a build.log; \
+	    fi;\
+	    if [ "$(VXWORKS_RTOS)" == "YES" ]; then \
+		if [ -f $${member}/lcu/src/Makefile ]; then \
+		    $(ECHO) "############ $${member} LCU" | tee -a build.log;\
+                    $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ clean >> build.log 2>& 1;\
+                    $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ all >> build.log 2>& 1 || echo "### ==> FAILED all ! " | tee -a build.log; \
+                    $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ install >> build.log 2>& 1 || echo "### ==> FAILED install ! " | tee -a build.log; \
+		fi;\
+	    fi;\
+	done;\
+	true;
+	@$(ECHO) "############ DONE (Re-)build $(SUBSYSTEM) Software    #################"| tee -a build.log
+# Update of all core components
+# This does also make man and does clenup at the end.
+# We use a define for the procedure of a single module, so that
+# we can reuse it also in the update_clean_test target further down.
+
+define update-clean-one-module
+	if [ ! -d $${member} ]; then \
+            echo "######## ==> $${member} MODULE NOT FOUND! FAILED! " | tee -a build.log;\
+        fi;\
+	if [ -f $${member}/src/Makefile ]; then \
+	    $(ECHO) "############ $${member} MAIN" | tee -a build.log;\
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ clean >> build.log 2>& 1;\
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ all >> build.log 2>& 1 || echo "### ==> FAILED all ! " | tee -a build.log; \
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ man >> build.log 2>& 1 || echo "### ==> FAILED man ! " | tee -a build.log; \
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ install >> build.log 2>& 1 || echo "### ==> FAILED install ! " | tee -a build.log; \
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/src/ clean >> build.log 2>& 1 || echo "### ==> FAILED clean ! " | tee -a build.log; \
+	elif [ -f $${member}/ws/src/Makefile ]; then \
+	    $(ECHO) "############ $${member} WS" | tee -a build.log;\
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ clean >> build.log 2>& 1;\
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ all >> build.log 2>& 1 || echo "### ==> FAILED all ! " | tee -a build.log; \
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ man >> build.log 2>& 1 || echo "### ==> FAILED man ! " | tee -a build.log; \
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ install >> build.log 2>& 1 || echo "### ==> FAILED install ! " | tee -a build.log; \
+                         $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/src/ clean >> build.log 2>& 1 || echo "### ==> FAILED clean ! " | tee -a build.log; \
+	fi;\
+	if [ "$(VXWORKS_RTOS)" == "YES" ]; then \
+	    if [ -f $${member}/lcu/src/Makefile ]; then \
+		$(ECHO) "############ $${member} LCU" | tee -a build.log;\
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ clean >> build.log 2>& 1;\
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ all >> build.log 2>& 1 || echo "### ==> FAILED all ! " | tee -a build.log; \
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ man >> build.log 2>& 1 || echo "### ==> FAILED man ! " | tee -a build.log; \
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ install >> build.log 2>& 1 || echo "### ==> FAILED install ! " | tee -a build.log; \
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/src/ clean >> build.log 2>& 1 || echo "### ==> FAILED clean ! " | tee -a build.log; \
+	    fi;\
+	fi
+endef
+
+# There is a 'true' at the end of the loop to ensure that if the LAST
+# module fails the whole Make does not fail
+#
+update_clean:
+	@$(ECHO) "############ (Re-)build $(SUBSYSTEM) Software         #################"| tee -a build.log
+	@for member in  $(foreach name, $(MODULES), $(name) ) ; do \
+            $(update-clean-one-module);\
+	done;\
+        true;
+	@$(ECHO) "############ DONE (Re-)build $(SUBSYSTEM) Software    #################"| tee -a build.log
 #
 # Test target
 #
 
+#
+# Check if the ACS_INSTANCE variable is defined
+# This allows to check for a clean test environment.
+#
+ifdef ACS_INSTANCE
+    MAKE_TEST_ACS_INSTANCE = $(ACS_INSTANCE)
+else
+    MAKE_TEST_ACS_INSTANCE = 0
+endif
+
+# We use a define for the procedure of a single module, so that
+# we can reuse it also in the update_clean_test target further down.
+
+define test-one-module
+	if [ -d $(ACSDATA)/tmp/ACS_INSTANCE.$(MAKE_TEST_ACS_INSTANCE) ]; then \
+	    $(ECHO) "############ $${member}: WARNING: ACS_INSTANCE.$(MAKE_TEST_ACS_INSTANCE) NOT CLEAN!  ############" | tee -a test.log ;\
+	fi;\
+	if [ -f $${member}/ws/test/Makefile ]; then\
+	    $(ECHO) "############ $${member}/ws/test WS TEST ############" | tee -a test.log ;\
+            if [ -f $${member}/lcu/test/Makefile ]; then \
+                $(MAKE) $(MAKE_FLAGS) -C $${member}/lcu/test/ all >> test.log 2>& 1 || echo "### ==> FAILED all lcu/test/! " | tee -a test.log; \
+            fi;\
+            $(MAKE) $(MAKE_FLAGS) -C $${member}/ws/test/ all >> test.log 2>& 1 || echo "### ==> FAILED all ws/test/! " | tee -a test.log; \
+            cd $${member}/ws/test/; export MAKE_PURE; tat -nc -v 2>& 1 | tee -a test.log |  egrep  '(Nothing to|FAILED.|PASSED.|Error:)'; cd $(startupDir); \
+	elif [ -f $${member}/test/Makefile ]; then\
+	    $(ECHO) "############ $${member}/test MAIN TEST ############" | tee -a test.log ;\
+	    $(MAKE) -k -C $${member}/test/ test | tee -a test.log |  egrep  '(Nothing to|FAILED.|PASSED.|Error:)';\
+	else\
+	    $(ECHO) "######## ==> $${member} TEST DIRECTORY STRUCTURE NOT FOUND! CANNOT TEST ANYTHING!" | tee -a test.log ;\
+	fi
+endef
+
 .PHONY: test
 
 Test = test
-$(Test):
-	@$(ECHO) "############ Clean Test Log File: test.log #################"
-	@rm -f test.log
-	@touch test.log
+#
+# If running on a machine where VxWorks is ocnfigured and tests have to be urn on the LCU.
+# $(ACCDB_CONFIG) will be defined and the target accdb_config will be called to
+# reconfigure the acc database in a clean way.
+#
+$(Test): clean_test_log $(ACCDB_CONFIG)
 	@$(ECHO) "############ TEST $(SUBSYSTEM) Software #################"| tee -a test.log
 	@for member in $(foreach name,$(MODULES),$(name)); do\
-		if [ -d $${member}/ws/test ]; then\
-			$(ECHO) "############ $${member}/ws/test WS TEST ############" | tee -a test.log ;\
-			$(MAKE) -k -C $${member}/ws/test/ $@ | tee -a test.log | egrep '(Nothing to|FAILED.|PASSED.|Error:)';\
-			if [ -d $${member}/lcu/test ]; then\
-				$(ECHO) "############ $${member}/lcu/test LCU TEST ############" | tee -a test.log;\
-				$(MAKE) -k -C $${member}/lcu/test/ $@ | tee -a test.log | egrep '(Nothing to|FAILED.|PASSED.|Error:)';\
-			fi;\
-		elif [ -d $${member}/test ]; then\
-			$(ECHO) "############ $${member}/test MAIN TEST ############" | tee -a test.log ;\
-			$(MAKE) -k -C $${member}/test/ $@ | tee -a test.log | egrep '(Nothing to|FAILED.|PASSED.|Error:)';\
-		else\
-			$(ECHO) "### ==> $${member} TEST DIRECTORY STRUCTURE NOT FOUND! FAILED!" | tee -a test.log ;\
-		fi;\
-	done
-	@$(ECHO) "... done"
+                   $(test-one-module);\
+	done;\
+        true;
+	@$(ECHO) "############ DONE TEST $(SUBSYSTEM) Software    #################"| tee -a test.log
+
+
+update_clean_test: clean_test_log $(ACCDB_CONFIG)
+	@$(ECHO) "############ UPDATE and TEST $(SUBSYSTEM) Software #################"| tee -a build.log
+	@for member in $(foreach name,$(MODULES),$(name)); do\
+                   $(update-clean-one-module);\
+                   $(test-one-module);\
+	done;\
+        true;
+	@$(SHELL)  $(MODULE_PREFIX)/acsBUILD/src/acsBUILDAfterBuildMod.sh >> build.log 2>& 1
+	@$(ECHO) "############ DONE UPDATE and TEST $(SUBSYSTEM) Software    #################"| tee -a build.log
+
+
+#
+# show_modules target
+#
+# Simply lists all MODULES that would be build
+# with the current setup
+#
+show_modules:
+	@$(ECHO) "Modules in build list are:" 
+	@$(ECHO) ${MODULES}
+
 #
 # Standard canned targets
 #
@@ -219,10 +301,6 @@ install:
 
 man:
 	$(canned)
-
-buildClean: build clean
-
-buildMan: build man
 
 #
 # ___oOo___
