clean of ACS_INSTANCE.n dirs added
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@101293 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/LGPL/CommonSoftware/acsdaemon/ws/test/acsdaemonTATEpilogue b/LGPL/CommonSoftware/acsdaemon/ws/test/acsdaemonTATEpilogue
--- a/LGPL/CommonSoftware/acsdaemon/ws/test/acsdaemonTATEpilogue
+++ b/LGPL/CommonSoftware/acsdaemon/ws/test/acsdaemonTATEpilogue
@@ -1,4 +1,6 @@
 #! /bin/bash
+. acsstartupAcsInstance
+
 #*******************************************************************************
 # ALMA - Atacama Large Millimiter Array
 # (c) Associated Universities Inc., 2002 
@@ -21,7 +23,7 @@
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 # MA 02111-1307  USA
 #
-# "@(#) $Id: acsdaemonTATEpilogue,v 1.2 2008/12/01 13:39:56 msekoran Exp $"
+# "@(#) $Id: acsdaemonTATEpilogue,v 1.3 2008/12/18 12:33:33 msekoran Exp $"
 #
 # who       when      what
 # --------  --------  ----------------------------------------------
@@ -29,5 +31,10 @@
 echo " ****************** TATEpilogue *************** "
 
 acsdaemonImpStopAll
+
+#INSTANCE_DIR=`getInstanceDirName $ACS_INSTANCE`
+#echo "Freeing $INSTANCE_DIR"
+#rm -rf $INSTANCE_DIR &> /dev/null || (echo "Cannot remove $INSTANCE_DIR")
+acsdataClean -all
 
 echo "*** done ***"
