JacORB profiling patch added
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@116401 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/ExtProd/INSTALL/buildJacORB b/ExtProd/INSTALL/buildJacORB
--- a/ExtProd/INSTALL/buildJacORB
+++ b/ExtProd/INSTALL/buildJacORB
@@ -2,7 +2,7 @@
 #*******************************************************************************
 # E.S.O. - ACS project
 #
-# "@(#) $Id: buildJacORB,v 1.19 2007/10/19 12:50:08 hsommer Exp $"
+# "@(#) $Id: buildJacORB,v 1.20 2009/09/18 10:29:58 msekoran Exp $"
 #
 # who       when      what
 # --------  --------  ----------------------------------------------
@@ -204,6 +204,29 @@ else
     rm $JACORB_SOURCES/JacORB-ACS-2007-10-19.patch
 fi
 
+
+#
+# JacORB ACS profiling patch
+#
+
+echo ==== ACS Profiling Patch
+if [ -f $JACORB_SOURCES/JacORB-ACS-profiling-2009-09-18.patch.gz ]
+then
+    gunzip -c $JACORB_SOURCES/JacORB-ACS-profiling-2009-09-18.patch.gz >$JACORB_SOURCES/JacORB-ACS-profiling-2009-09-18.patch
+else
+    echo "file $JACORB_SOURCES/JacORB-ACS-profiling-2009-09-18.patch.gz not found"
+    echo "Installation aborted"
+    exit 3
+fi
+patch -p1 < $JACORB_SOURCES/JacORB-ACS-profiling-2009-09-18.patch
+if [ $? -ne 0 ]
+then
+    rm $JACORB_SOURCES/JacORB-ACS-profiling-2009-09-18.patch
+    echo "========= FAILED =========="
+        exit 1
+else
+    rm $JACORB_SOURCES/JacORB-ACS-profiling-2009-09-18.patch
+fi
 
 echo "========= Done with unpacking and patching, can compile now... =========="
 
