ported to new ACE+TAO x.5.2    * DsLogAdmin.idl from TAO includes tao/TimeBase.pidl what was    solved by copying tao/TimeBase.idl    * some TAO IDL files includes CosProperty.idl (in past    CosPropertyService.idl) what was solved by creating a link
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@56922 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/ExtProd/INSTALL/buildJacORB b/ExtProd/INSTALL/buildJacORB
--- a/ExtProd/INSTALL/buildJacORB
+++ b/ExtProd/INSTALL/buildJacORB
@@ -2,7 +2,7 @@
 #*******************************************************************************
 # E.S.O. - ACS project
 #
-# "@(#) $Id: buildJacORB,v 1.13 2006/07/25 14:21:10 gchiozzi Exp $"
+# "@(#) $Id: buildJacORB,v 1.14 2006/08/09 10:45:42 bjeram Exp $"
 #
 # who       when      what
 # --------  --------  ----------------------------------------------
@@ -195,12 +195,20 @@ then
      echo "========= FAILED =========="
 	exit 1
 fi
+mkdir tao
+cp $ACE_ROOT/TAO/tao/TimeBase.pidl tao/
+if [ $? -ne 0 ]
+then
+     echo "========= FAILED =========="
+	exit 1
+fi
 cp $ACE_ROOT/TAO/orbsvcs/orbsvcs/AVStreams.idl .
 if [ $? -ne 0 ]
 then
      echo "========= FAILED =========="
 	exit 1
 fi
+ln -s CosPropertyService.idl CosProperty.idl
 cd $JACORB_HOME/idl
 
 ant property
