Fixed in order to checkout RTIDDS when -c switch is set in the command line
git-svn-id: https://svn.alma.cl/p2/trunk/ACS@211975 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/ExtProd/INSTALL/installRTIDDS b/ExtProd/INSTALL/installRTIDDS
--- a/ExtProd/INSTALL/installRTIDDS
+++ b/ExtProd/INSTALL/installRTIDDS
@@ -47,14 +47,19 @@ ACRO_READER=$?
 if [ "$1" == "-c" ]
 then
     echo "Checking out RTIDDS (host tar $HOST_TAR for target $TARGET_TAR)"
-    SVN_URL=`svn info $0|grep URL`
-    RTIDDS_SVN_URL=`expr match "$SVN_URL" '.*\(https.*ExtProd\)'`
-    echo "Checking out $RTIDDS_SVN_URL"
-
-    svn co "$RTIDDS_SVN_URL/PROPRIETARY/RTIDDS"
+    cd ..
+    svn up PROPRIETARY --depth files
     if [ $? != 0 ]
     then
-        echo "ERROR: Cold not svn co: ACS/ExtProd/PROPRIETARY/RTIDDS"
+        echo "ERROR: Could not svn co: ACS/ExtProd/PROPRIETARY"
+        exit 4
+    fi
+    cd PROPRIETARY
+    svn up RTIDDS
+
+    if [ $? != 0 ]
+    then
+        echo "ERROR: Could not svn co: ACS/ExtProd/PROPRIETARY/RTIDDS"
         exit 4
     fi
     DDS_DIR=$PWD/RTIDDS
