now we can install RTI DDS depend on OS/gcc version
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@201488 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/ExtProd/INSTALL/installRTIDDS b/ExtProd/INSTALL/installRTIDDS
--- a/ExtProd/INSTALL/installRTIDDS
+++ b/ExtProd/INSTALL/installRTIDDS
@@ -1,28 +1,46 @@
 #! /bin/bash
 
 ARCH=`uname -m`
+GCC_VERSION_MAJOR=`echo __GNUC__ | gcc -E -xc - | tail -n 1`
+GCC_VERSION_MINOR=`echo __GNUC_MINOR__ | gcc -E -xc - | tail -n 1`
+
 DDS_DIR=$PWD/../PROPRIETARY/RTIDDS/
 
 if [ $ARCH == x86_64 ]
 then
-    HOST_TAR=rtidds45f-host-x64Linux.tar.gz.gpg
-    TARGET_TAR=rtidds45f-target-x64Linux2.6gcc4.1.2.tar.gz.gpg
+	BIT_ARCH=x64
+#    HOST_TAR=rtidds45f-host-x64Linux.tar.gz.gpg
+#    TARGET_TAR=rtidds45f-target-x64Linux2.6gcc4.1.2.tar.gz.gpg
 else
     if [ $ARCH == i386 -o $ARCH == i686 ]
     then
-    HOST_TAR=rtidds45f-host-i86Linux.tar.gz.gpg
-    TARGET_TAR=rtidds45f-target-i86Linux2.6gcc4.1.2.tar.gz.gpg
+    BIT_ARCH=i86
+    
     else
     echo "ERROR: not supported platform: $ARCH"
     exit 2
     fi
 fi
 
-# do we have acrobatreader on the machine ?
+
+if [ $GCC_VERSION_MAJOR == 4 ]
+then
+	if [ $GCC_VERSION_MINOR -ge 4 ]
+	then
+		GCC_VER=4.4.5
+	else
+		GCC_VER=4.1.2
+	fi
+else
+    echo "ERROR: not supported gcc version: $GCC_VERSION_MAJOR"
+    exit 3
+fi
+
+# do we have acrobat reader on the machine ?
 which acroread 2&>1 /dev/null
 ACRO_READER=$?
 
-# if option -c is specified we check out all neccessary files
+# if option -c is specified we check out all necessary files
 if [ "$1" == "-c" ]
 then
     echo "Checking out RTIDDS (host tar $HOST_TAR for target $TARGET_TAR)"
