COMP-2736 reports documentation problems with acsutilAwaitContainerStart and acsutilTATPrologue.  Both scripts have been modified to display usage information if -h or --help options are supplied.  Rudimentary parameter checking has also been added to acsutilAwaitContainerStart.
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@103851 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/LGPL/CommonSoftware/acsutil/ws/src/acsutilAwaitContainerStart b/LGPL/CommonSoftware/acsutil/ws/src/acsutilAwaitContainerStart
--- a/LGPL/CommonSoftware/acsutil/ws/src/acsutilAwaitContainerStart
+++ b/LGPL/CommonSoftware/acsutil/ws/src/acsutilAwaitContainerStart
@@ -1,5 +1,29 @@
 #!/bin/bash
 #--------------------------------------------------
+
+# A helpful message describing how this command works
+function printUsage
+{
+	echo "Usage: `basename $0` [OPTIONS] type_of_container name_of_container"
+	echo "Wait for the named container to start."
+	echo ""
+	echo "Options:"
+	echo "-h, --help      Prints this message and exits"
+	
+}
+
+if [ "$1" = "-h" -o "$1" = "--help" ] ; then
+    printUsage;
+    exit 0;
+fi
+
+if [ "$#" -ne "2" ] ; then
+	echo "Error: wrong number of parameters provided"
+    printUsage;
+    exit 1;
+fi
+
+# Now the actual work gets done
 #first need to figure out $ACS_TMP
 if [ "$ACS_TMP" = "" ]
 then 
