COMP-8312: moved the check for the error before the check for the expected output so that it takes precedence. So now the script is exiting as soon as the error string is detected. Fixed a bug with the -t (timeout) option that was waiting 1 second more than what was specified by the user.
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@188930 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/LGPL/CommonSoftware/acsutil/ws/src/acsutilBlock b/LGPL/CommonSoftware/acsutil/ws/src/acsutilBlock
--- a/LGPL/CommonSoftware/acsutil/ws/src/acsutilBlock
+++ b/LGPL/CommonSoftware/acsutil/ws/src/acsutilBlock
@@ -145,8 +145,8 @@ fi
 MAX_TIMEOUT=$CL_TIMEOUT
 STD_SLEEP=1
 
-i="0"
-while [ "$i" ]
+i="1"
+while true
 do
   sleep $STD_SLEEP
 
@@ -184,6 +184,13 @@ do
   if [ "X$completed" != "X" ] 
   then
       break
+  
+  elif [ "$something_bad" != "" ]
+  then
+      echo "Detected the process emitted '$CL_CRAP' which implies"
+      echo "some sort of error condition!"
+      echo "Bailing without making any attempt to stop the process."
+      exit 5
  
   #process is gone and it never emitted the correct output
   elif [ "$pidExists" = "" ] && [ "$CL_STRING" != "" ]
@@ -196,13 +203,7 @@ do
   then
       break
 
-  elif [ "$something_bad" != "" ]
-  then
-      echo "Detected the process emitted '$CL_CRAP' which implies"
-      echo "some sort of error condition!"
-      echo "Bailing without making any attempt to stop the process."
-      exit 5
-  fi
+ fi
 
   #check if we've waited too long.
   if [ "$i" = "$MAX_TIMEOUT" ]
