Changes in regard to COMP-4482 and COMP-4305. Logs and files should be stored in instance-specific directory.
git-svn-id: https://alma-svn.aoc.nrao.edu/p2/trunk/ACS@139427 523d945c-050c-4681-91ec-863ad3bb968a

diff --git a/LGPL/CommonSoftware/acsutil/ws/src/acsutilTATEpilogue b/LGPL/CommonSoftware/acsutil/ws/src/acsutilTATEpilogue
--- a/LGPL/CommonSoftware/acsutil/ws/src/acsutilTATEpilogue
+++ b/LGPL/CommonSoftware/acsutil/ws/src/acsutilTATEpilogue
@@ -4,8 +4,17 @@
 
 if [ "`uname`" = "Linux" ]; then enable -n echo; fi
 
+export ACS_INSTANCE=`cat $ACS_TMP/acs_instance`
+if [ "$ACS_INSTANCE" = "" ]
+then
+    echo "Could not determine the ACS_INSTANCE!"
+    echo "Exiting!"
+    exit 1
+fi
+
 # check if we need to stop logging client process(es) that may have been started in acsutilTATPrologue
-pidfile=$ACS_TMP/loggingClient.pid
+INSTANCE_DIR=$ACS_TMP/ACS_INSTANCE.$ACS_INSTANCE
+pidfile=$INSTANCE_DIR/loggingClient.pid
 if [ -r $pidfile ] ; then
 	echo going about $pidfile...
 	pids=`cat $pidfile`
@@ -23,14 +32,6 @@ if [ -r $pidfile ] ; then
 	done      
 	#echo Failed: $failed
 	echo -n $failed > $pidfile
-fi
-
-export ACS_INSTANCE=`cat $ACS_TMP/acs_instance`
-if [ "$ACS_INSTANCE" = "" ]
-then
-    echo "Could not determine the ACS_INSTANCE!"
-    echo "Exiting!"
-    exit 1
 fi
 
 
